### ISSUE TITLE
Zip of macOS .app prevents it from running

### ISSUE THREAD

**Issue by sfyfe31** [archiverjs/node-archiver#225] opened 2017-03-14 12:23 UTC
I'm using `archiver` as part of the build process for an [Electron](https://electron.atom.io) app. I create a directory containing the macOS `.app` executable. Before creating the zip, the `.app` runs fine. The one inside the resulting `.zip` however doesn't open. Just appears in the macOS dock for a split second and disappears.

I'm also adding a `README.txt` on the fly in the zip, which opens fine.

Oddly, the Windows and Linux executables are unaffected and both work fine from the `.zip`.

Could `archiver` change a `.app` file, to prevent it from working?

Here's what I'm doing:

```
const output = fs.createWriteStream(`${exeRoot}.zip`)
output.on('close', () => {
  console.log(chalk.red(`Deleting "${tempDir}"`))
  fs.remove(`${tempDir}`, err => {
    if (err) { throw err }
  })
})

const archive = archiver('zip')
archive.on('error', err => { throw err })
archive.pipe(output)

archive.directory(`${tempDir}/${exeRoot}`, `${exeRoot}`)
archive.append(readMe, { name: 'README.txt' })
archive.finalize()
``` 

I've also tried using `store`, to prevent any compression, but it makes no difference

```
const archive = archiver('zip', { store: true })
```

**Comment by ctalkington** [comment] 2017-03-15 02:41
i would guess you are losing the executable bit that or theres some security policy in place. archiver doesnt alter content beyond compression. you tried with STORE which is what i would of also advised so likely is permissions. I think theres another issue running around about such.

permissions are not auto-copied from fs and symlinks arent preserved if any of that applies here.

**Comment by ctalkington** [comment] 2017-03-15 02:49
are you sure the path within zip is proper, maybe trying with `false` instead of `${exeRoot}` for the destination. that will put your files at root of zip.

**Comment by sfyfe31** [comment] 2017-03-15 09:39
Didn't make any difference

**Comment by lachenmayer** [comment] 2017-03-20 21:39
Hi there, I've spent the last couple of days investigating a very similar bug in my own app. The issue I had is that I would get an "Operation not permitted" error from the macOS unarchiver, and even if I unzipped it on the command-line using `unzip`, the app would not run.

The bug is not in archiver, but in Electron. It is due to their monkey-patching of `fs` to support [.asar](https://github.com/electron/asar) files. The issue is that, in Electron, `fs.stat` pretends that any file ending in `.asar` is actually a directory.

In the original app `Resources` directory, there is a file called `electron.asar`. When inspecting the contents of the zip file, using `unzip -l <file> | grep asar`, I found that archiver had indeed dutifully copied all the files referenced in the `.asar` file as files & subdirectories. Also, .asar files don't save permissions information with the files, so that's where the permissions error from the system unarchiver comes from.

The correct workaround is to set `process.noAsar = true`, as described in the [Electron packaging docs](https://electron.atom.io/docs/tutorial/application-packaging/#treating-an-asar-archive-as-a-normal-file). This didn't work properly for me for some reason, so I instead now spawn a child process using `child_process.fork`, and set `process.noAsar = true` in there.

Moral of the story: don't monkey-patch core modules...

---

For completeness/links - separate mentions of the same bug:
- electron/electron#2446
- electron/electron#3395

Other workarounds:
- electron/electron#7479 (`ELECTRON_NO_ASAR` env variable for child processes)
- electron/electron#2035 (monkey-patch fs again 🙄)

**Comment by ctalkington** [comment] 2017-03-20 22:11
@lachenmayer at what point did you set that process variable? how are adding files?

**Comment by sfyfe31** [comment] 2017-03-24 22:32
@lachenmayer I just tried adding `process.noAsar = true` but as you found, it didn't work. How exactly did you spawn a child process?

**Comment by lachenmayer** [comment] 2017-03-26 19:44
parent.js

```js
const child_process = require('child_process')
const child = child_process.fork(path.join(__dirname, 'child.js'))
```

child.js

```js
process.noAsar = true
const archiver = require('archiver')
const fs = require('fs')
// do all your archiving biz here
```

You can either pass args to the process, or use `process.send` & `process.on('message', m => ...)` to communicate with the child process.

Instead of `process.noAsar = true`, you can set the `ELECTRON_NO_ASAR` env variable as described in https://github.com/electron/electron/pull/7479.

**Comment by sfyfe31** [comment] 2017-03-28 18:20
Unfortunately neither worked. I tried:

`build-zip-container.js`
```
const child_process = require('child_process')
const child = child_process.fork('build-zip.js')
```

`build-zip.js`
```
process.noAsar = true
const fs = require('fs-extra')
const archiver = require('archiver')
// zipping up of files
```

and

`build-zip-container.js`
```
const child_process = require('child_process')
const child = child_process.fork('build-zip.js', { env: { 'ELECTRON_NO_ASAR': 'true' }})
```

`build-zip.js`
```
const fs = require('fs-extra')
const archiver = require('archiver')
// zipping up of files
```

In both cases, when I then unzip and run the macOS app, I get this:

```
Process:               vDrive [4370]
Path:                  /Users/USER/Downloads/*/vDrive.app/Contents/MacOS/vDrive
Identifier:            com.electron.vdrive
Version:               0.0.1 (0.0.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           vDrive [4370]
User ID:               501

Date/Time:             2017-03-28 19:03:31.777 +0100
OS Version:            Mac OS X 10.12.4 (16E195)
Report Version:        12
Anonymous UUID:        2DD120A0-5CF4-7726-E74E-C69FE9C93A25

Sleep/Wake UUID:       8548C19A-3B4C-420A-8CF3-3BE523D72FC3

Time Awake Since Boot: 29000 seconds
Time Since Wake:       4700 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/USER/Downloads/*/vDrive.app/Contents/MacOS/vDrive
  Reason: image not found

Binary Images:
       0x10c4da000 -        0x10c4dafff +com.electron.vdrive (0.0.1 - 0.0.1) <840167AE-5E41-3AF5-8425-4861511E4BFB> /Users/USER/Downloads/*/vDrive.app/Contents/MacOS/vDrive
       0x112e81000 -        0x112ebedc7  dyld (433.5) <8239D0D7-66F6-3C44-A77F-586F74525DA3> /usr/lib/dyld

Model: MacBookPro13,2, BootROM MBP132.0226.B15, 2 processors, Intel Core i5, 2.9 GHz, 16 GB, SMC 2.37f20
Graphics: Intel Iris Graphics 550, Intel Iris Graphics 550, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
Memory Module: BANK 1/DIMM0, 8 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C31473332443450472D30393320
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x157), Broadcom BCM43xx 1.0 (7.21.171.124.1a2)
Bluetooth: Version 5.0.4f18, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
USB Device: iBridge
Thunderbolt Bus: MacBook Pro, Apple Inc., 15.14
Thunderbolt Bus: MacBook Pro, Apple Inc., 15.14
```

**Comment by lachenmayer** [comment] 2017-03-31 12:39
`/Users/USER/Downloads/*/vDrive.app/Contents/MacOS/vDrive`

The `*` in that path is odd - is that intentional?

**Comment by sfyfe31** [comment] 2017-03-31 12:42
It's just the macOS error copied and pasted. I was running the .app executable from the unzipped folder in my downloads folder

**Comment by lachenmayer** [comment] 2017-03-31 15:02
DYLD and `@rpath` etc are black magic to me, but a helpful method for debugging if anything is messed up in the resulting folder is to diff the folder contents. eg:

```bash
ls -R /path/to/original.app/ > original
ls -R /path/to/unzipped.app/ > zipped
diff original zipped
```

**Comment by lachenmayer** [comment] 2017-04-10 14:35
Hi there, I've now come across this issue myself too.

You can see below that the working framework directory has several symlinks, while the broken one does not.

```
$ ls -la ___WORKING___/Contents/Frameworks/Electron\ Framework.framework/
total 24
drwxr-xr-x  6 harry  staff  204 10 Apr 14:43 .
drwxr-xr-x  9 harry  staff  306 10 Apr 14:43 ..
lrwxr-xr-x  1 harry  staff   35 10 Apr 14:43 Electron Framework -> Versions/Current/Electron Framework
lrwxr-xr-x  1 harry  staff   26 10 Apr 14:43 Libraries -> Versions/Current/Libraries
lrwxr-xr-x  1 harry  staff   26 10 Apr 14:43 Resources -> Versions/Current/Resources
drwxr-xr-x  4 harry  staff  136 10 Apr 14:43 Versions
```

```
$ ls -la ___BROKEN___/Contents/Frameworks/Electron\ Framework.framework/
total 0
drwxr-xr-x@ 3 harry  staff  102 10 Apr 15:19 .
drwxr-xr-x@ 9 harry  staff  306 10 Apr 15:19 ..
drwxr-xr-x@ 3 harry  staff  102 10 Apr 15:19 Versions
```

The 'solution' for this bug is described in https://github.com/atom/atom/issues/9114#issuecomment-270232363

> You'll want to resolve all of the links, so replace everything in app/Contents/Frameworks/Electron Framework.framework/ with everything in app/Contents/Frameworks/Electron Framework.framework/versions/A and do this for the rest of the frameworks.

The issue is due to archiver not copying symlinks. I've seen that work on symlinks is being done by @ctalkington on this, see https://github.com/archiverjs/node-archiver/issues/158 and linked issues.

I'm sure that once that's solved, this issue can be closed :)

**Comment by sfyfe31** [comment] 2017-04-12 23:40
Thanks so much @lachenmayer! That worked beautifully. Before zipping up my apps, I get all the frameworks in `AppName.app/Contents/Frameworks`, then copy the contents of `Versions/A` into the  root of the `.framework` folder, overwriting the symlinks. Hopefully they'll eventually fix this in the Electron build process, but until then, I now know to do this :)

**Comment by lachenmayer** [comment] 2017-04-13 10:26
Can we please reopen this - I would like the user to be able to zip arbitrary files.
The issue doesn't really have anything to do with Electron - any app on macOS that uses bundled frameworks will have the sam problem.

**Comment by sfyfe31** [comment] 2017-04-13 10:30
Sorry @lachenmayer, I had perceived this as an issue with how `electron-forge`  creates symlinks in the Frameworks, so I closed this one and [raised an issue with that repository](https://github.com/electron-userland/electron-forge/issues/196). I'm not entirely familiar with the contents of `.app` executables, so if it's common practice outside of `electron`, then it would be ideal if `node-archiver` could do some work with detecting and preserving symlinks

**Comment by herrjemand** [comment] 2017-05-04 05:32
It's an issues of broken symlinks. Does archiver has option to preserve symlinks?

**Comment by ctalkington** [comment] 2017-05-09 03:39
currently theres no option, i have been working on supporting the underlying zip specification for symlinks so that some day (hopefully in the near future) an option can be added for the fs based methods of archiver.

**Comment by ctalkington** [comment] 2017-06-17 17:45
symlink support is coming in v2.0.0 and id love to see if it helps this issue. for now, im closing but anyone having issues after thats released, should definitely open a new issue so we can enhance symlink handling for even more use cases.

**Closed by ctalkington** 2017-06-17 17:45 UTC
