### ISSUE TITLE
Error: "directory: build\releases\darwin\x64\2.7.0-dev/G-Craft_Client.app/"

### ISSUE THREAD

**Issue by MattCowley** [archiverjs/node-archiver#257] opened 2017-06-24 17:00 UTC
What does the error "directory: build\releases\darwin\x64\2.7.0-dev/G-Craft_Client.app/" mean?
I can't get the on error to output anything more and this error is pretty meaningless to me. The zip is still created, but appears to be corrupt.

**Comment by soyuka** [comment] 2017-06-25 17:42
Might be related to https://github.com/archiverjs/node-archiver/issues/225?

**Comment by MattCowley** [comment] 2017-06-27 16:19
The zip is corrupt and will not open even on windows.

**Comment by soyuka** [comment] 2017-06-27 16:30
Yes indeed, and you're trying to zip a `.app`. I assume it's then a duplicate of #225.

**Comment by MattCowley** [comment] 2017-06-27 16:32
#225 Doesn't mention the archive being corrupt in windows at all? It just says the app becomes unusable. That is due to windows not following symlinks which is a quick hotfix. My issue doesn't appear to be that though, as the archive is corrupt even on windows.

**Comment by soyuka** [comment] 2017-06-27 16:35
Okay then! Are you able to give me something I can reproduce?

**Comment by MattCowley** [comment] 2017-06-27 16:37
Sadly I haven't yet reproduced it :/
When it failed, I moved to a different archive library, trying to reproduce the issue again with this library I have been unable to repro yet.

**Comment by ctalkington** [comment] 2017-07-05 23:38
closing due to lack of reproducible example. if anyone can provide more detail feel free to open a new issue.

**Closed by ctalkington** 2017-07-05 23:38 UTC
